<a href="https://colab.research.google.com/github/MahmudGalib7/AI-Olympiad/blob/master/data_analysis/notebook/learning_numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

### Load in NumPy (remember to pip install numpy first)

In [1]:
import numpy as np

In [21]:
arr = np.array([[1,0,0],[0,1,2]], dtype="complex")
arr

array([[1.+0.j, 0.+0.j, 0.+0.j],
       [0.+0.j, 1.+0.j, 2.+0.j]])

In [9]:
arr.ndim

2

In [10]:
arr.shape

(2, 3)

In [11]:
arr.size
arr.itemsize
arr.size * arr.itemsize
arr.nbytes

48

In [20]:
arr.dtype

dtype('complex128')

In [19]:
arr.data

In [27]:
x = np.zeros((3,4))
x

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [28]:
y = np.ones((3,3))
y

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [30]:
z = np.full((4,4), 9)
z

array([[9, 9, 9, 9],
       [9, 9, 9, 9],
       [9, 9, 9, 9],
       [9, 9, 9, 9]])