<a href="https://colab.research.google.com/github/MahmudGalib7/AI-Olympiad/blob/master/data_analysis/notebook/learning_numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

### Load in NumPy (remember to pip install numpy first)

In [2]:
import numpy as np

In [22]:
arr = np.array([[1,2,3,4],[5,6,7,8]])
arr

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [ ]:
arr.ndim

2

In [ ]:
arr.shape

(2, 3)

In [ ]:
arr.size
arr.itemsize
arr.size * arr.itemsize
arr.nbytes

48

In [ ]:
arr.dtype

dtype('complex128')

In [ ]:
arr.data

In [ ]:
x = np.zeros((3,4))
x

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [ ]:
y = np.ones((3,3))
y

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [ ]:
z = np.full((4,4), 9)
z

array([[9, 9, 9, 9],
       [9, 9, 9, 9],
       [9, 9, 9, 9],
       [9, 9, 9, 9]])

In [10]:
np.empty((2, 3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [9]:
np.arange(10, 30, 5)

array([10, 15, 20, 25])

In [12]:
np.linspace(0, 2, 9)
x = np.linspace(0, 2 * np.pi, 100)
x
np.sin(x)

array([ 0.00000000e+00,  6.34239197e-02,  1.26592454e-01,  1.89251244e-01,
        2.51147987e-01,  3.12033446e-01,  3.71662456e-01,  4.29794912e-01,
        4.86196736e-01,  5.40640817e-01,  5.92907929e-01,  6.42787610e-01,
        6.90079011e-01,  7.34591709e-01,  7.76146464e-01,  8.14575952e-01,
        8.49725430e-01,  8.81453363e-01,  9.09631995e-01,  9.34147860e-01,
        9.54902241e-01,  9.71811568e-01,  9.84807753e-01,  9.93838464e-01,
        9.98867339e-01,  9.99874128e-01,  9.96854776e-01,  9.89821442e-01,
        9.78802446e-01,  9.63842159e-01,  9.45000819e-01,  9.22354294e-01,
        8.95993774e-01,  8.66025404e-01,  8.32569855e-01,  7.95761841e-01,
        7.55749574e-01,  7.12694171e-01,  6.66769001e-01,  6.18158986e-01,
        5.67059864e-01,  5.13677392e-01,  4.58226522e-01,  4.00930535e-01,
        3.42020143e-01,  2.81732557e-01,  2.20310533e-01,  1.58001396e-01,
        9.50560433e-02,  3.17279335e-02, -3.17279335e-02, -9.50560433e-02,
       -1.58001396e-01, -

In [23]:
arr.reshape((2,2,2))

array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]]])

In [24]:
arr + 2

array([[ 3,  4,  5,  6],
       [ 7,  8,  9, 10]])

In [25]:
arr - 2

array([[-1,  0,  1,  2],
       [ 3,  4,  5,  6]])

In [26]:
arr * 2

array([[ 2,  4,  6,  8],
       [10, 12, 14, 16]])

In [27]:
arr / 2

array([[0.5, 1. , 1.5, 2. ],
       [2.5, 3. , 3.5, 4. ]])

In [28]:
arr ** 2

array([[ 1,  4,  9, 16],
       [25, 36, 49, 64]])

In [30]:
np.sin(arr)

array([[ 0.84147098,  0.90929743,  0.14112001, -0.7568025 ],
       [-0.95892427, -0.2794155 ,  0.6569866 ,  0.98935825]])

In [31]:
np.cos(arr)

array([[ 0.54030231, -0.41614684, -0.9899925 , -0.65364362],
       [ 0.28366219,  0.96017029,  0.75390225, -0.14550003]])

In [32]:
np.tan(arr)

array([[ 1.55740772, -2.18503986, -0.14254654,  1.15782128],
       [-3.38051501, -0.29100619,  0.87144798, -6.79971146]])

In [34]:
arr % 2 == 0

array([[False,  True, False,  True],
       [False,  True, False,  True]])

In [35]:
A = np.array([[1, 1],[0, 1]])
B = np.array([[2, 0],[3, 4]])

In [38]:
A * B
A @ B
A.dot(B)

array([[5, 4],
       [3, 4]])

In [57]:
rg = np.random.default_rng(1)
a = np.ones((2,3), dtype=int)
b = rg.random((2,3))

a*=3
a
b+=a
b

array([[3.51182162, 3.9504637 , 3.14415961],
       [3.94864945, 3.31183145, 3.42332645]])

In [54]:
a = np.ones(3, dtype="int32")
b = np.linspace(0, np.pi, 3)
b.dtype.name
c = a + b
d = np.exp(c * 1)
d
d.dtype.name

'float64'

In [58]:
a = rg.random((2, 3))
a.sum()
a.min()
a.max()

np.float64(0.8277025938204418)

In [62]:
b = np.arange(12).reshape(3,4)
b
b.sum(axis=0)
b.min(axis=1)
b.cumsum(axis=1)

array([[ 0,  1,  3,  6],
       [ 4,  9, 15, 22],
       [ 8, 17, 27, 38]])

In [66]:
a = np.arange(3)
np.exp(a)
np.sqrt(a)
b = np.array([2, -1, 4])
np.add(a,b)

array([2, 0, 6])

In [68]:
a = np.array([True, True, False])
np.all(a)
np.any(a)

np.True_

In [69]:
data = np.array([10, 20, 30, 40, 50])
mean = np.mean(data)
std = np.std(data)
normalized = (data - mean) / std

print("Mean:", mean)
print("Std:", std)
print("Normalized:", normalized)

Mean: 30.0
Std: 14.142135623730951
Normalized: [-1.41421356 -0.70710678  0.          0.70710678  1.41421356]


In [71]:
scores = np.array([0.2, 0.5, 0.1, 0.9])

total = np.sum(scores)
max_score = np.max(scores)
max_index = np.argmax(scores)

print("Total:", total)
print("Max Score:", max_score)
print("Class with Max Score:", max_index)

Total: 1.7
Max Score: 0.9
Class with Max Score: 3


In [72]:
X = np.array([[1, 2], [3, 4]])
weights = np.array([0.5, -1.0])

predictions = np.dot(X, weights)
print("Predictions:", predictions)

Predictions: [-1.5 -2.5]


In [73]:
arr = np.arange(6)
reshaped = arr.reshape(2, 3)
transposed = reshaped.T

print("Original:", arr)
print("Reshaped:\n", reshaped)
print("Transposed:\n", transposed)

Original: [0 1 2 3 4 5]
Reshaped:
 [[0 1 2]
 [3 4 5]]
Transposed:
 [[0 3]
 [1 4]
 [2 5]]


In [74]:
data = np.array([1, 5, 10, 20])
capped = np.where(data > 10, 10, data)

print("Original:", data)
print("Capped:", capped)

Original: [ 1  5 10 20]
Capped: [ 1  5 10 10]


In [77]:
probs = np.array([0.3, 0.8, 0.5, 0.1])
sorted_indices = np.argsort(probs)[::-1]

print("Sorted indices (best to worst):", sorted_indices)
print("Sorted probs:", probs[sorted_indices])

Sorted indices (best to worst): [1 2 0 3]
Sorted probs: [0.8 0.5 0.3 0.1]


In [78]:
labels = np.array([1, 0, 1, 2, 0, 1, 2])
unique_classes, counts = np.unique(labels, return_counts=True)

print("Classes:", unique_classes)
print("Counts:", counts)

counts_bincount = np.bincount(labels)
print("Counts (bincount):", counts_bincount)

Classes: [0 1 2]
Counts: [2 3 2]
Counts (bincount): [2 3 2]


In [79]:
preds = np.array([0.1, 1.5, -0.3, 0.8])
clipped = np.clip(preds, 0, 1)  # Force to [0, 1] range

print("Original:", preds)
print("Clipped:", clipped)

Original: [ 0.1  1.5 -0.3  0.8]
Clipped: [0.1 1.  0.  0.8]


In [80]:
x = np.linspace(0, np.pi, 5)
print("Evenly spaced values between 0 and pi:", x)

Evenly spaced values between 0 and pi: [0.         0.78539816 1.57079633 2.35619449 3.14159265]


In [82]:
a = np.arange(10)**3
a
a[2]
a[2:5]
a[:6:2] = 1000
a
a[::-1]  # reversed a
for i in a:
    print(i**(1 / 3.))

9.999999999999998
1.0
9.999999999999998
3.0
9.999999999999998
4.999999999999999
5.999999999999999
6.999999999999999
7.999999999999999
8.999999999999998


In [95]:
def f(x,y):
  return 10 * x+y
b = np.fromfunction(f, (5,4), dtype=int)
b[2, 3]
b[0:5, 1]
b[:, 1]
b[1:3, :]
b[-1]

for row in b:
  print(row)

for element in b.flat:
  print(element)

[0 1 2 3]
[10 11 12 13]
[20 21 22 23]
[30 31 32 33]
[40 41 42 43]
0
1
2
3
10
11
12
13
20
21
22
23
30
31
32
33
40
41
42
43


In [97]:
c = np.array([[[  0,  1,  2],
               [ 10, 12, 13]],
              [[100, 101, 102],
               [110, 112, 113]]])
c.shape
c[..., 2]
c[1, ...]

array([[100, 101, 102],
       [110, 112, 113]])

In [96]:
x = 3.567
print('np.round:', np.round(x))
print('np.floor:', np.floor(x))
print('np.ceil:', np.ceil(x))
print('np.trunc:', np.trunc(x))
print('np.rint:', np.rint(x))
print('np.fix:', np.fix(x))

np.round: 4.0
np.floor: 3.0
np.ceil: 4.0
np.trunc: 3.0
np.rint: 4.0
np.fix: 3.0


In [108]:
x = np.array([[[  0,  1,  2],
               [ 10, 12, 13]],
              [[100, 101, 102],
               [110, 112, 113]]])
x.ravel()
x.reshape((6,2))
x.T
x.T.shape
x.shape

(2, 2, 3)

In [111]:
x.resize((2,6))
x.reshape((3, -1))

array([[  0,   1,   2,  10],
       [ 12,  13, 100, 101],
       [102, 110, 112, 113]])

In [112]:
a = np.floor(10 * rg.random((2, 2)))
a
b = np.floor(10 * rg.random((2, 2)))
b
np.vstack((a, b))
np.hstack((a, b))

array([[3., 7., 1., 4.],
       [3., 4., 2., 2.]])

In [120]:
np.column_stack((a,b))
p = np.array([4., 2.])
q = np.array([3., 8.])
np.column_stack((p, q))
p[:, np.newaxis]
np.column_stack((a[:,np.newaxis], b[:,np.newaxis]))
np.hstack((a[:, np.newaxis], b[:, np.newaxis]))

array([[[3., 7.],
        [1., 4.]],

       [[3., 4.],
        [2., 2.]]])

In [124]:
a = np.floor(10 * rg.random((2, 12)))
a
np.hsplit(a, 3)
np.hsplit(a, (3, 4))
np.vsplit(a, (3, 4))

[array([[3., 0., 2., 4., 1., 6., 3., 7., 6., 4., 8., 6.],
        [8., 3., 5., 1., 9., 2., 2., 0., 2., 7., 6., 1.]]),
 array([], shape=(0, 12), dtype=float64),
 array([], shape=(0, 12), dtype=float64)]

In [125]:
a = np.array([[ 0,  1,  2,  3],
              [ 4,  5,  6,  7],
              [ 8,  9, 10, 11]])
b = a
b is a

True

In [126]:
def f(x):
    print(id(x))
id(a)
f(a)

132322638807376


In [128]:
c = a.view()
c is a
c.base is a
c.flags.owndata
c = c.reshape((2, 6))
a.shape
c[0, 4] = 1234
a

True

In [129]:
d = a.copy()
d is a
d.base is a
d[0, 0] = 9999
a

array([[   0,    1,    2,    3],
       [1234,    5,    6,    7],
       [   8,    9,   10,   11]])

In [130]:
palette = np.array([[0, 0, 0],         # black
                    [255, 0, 0],       # red
                    [0, 255, 0],       # green
                    [0, 0, 255],       # blue
                    [255, 255, 255]])  # white
image = np.array([[0, 1, 2, 0],
                  [0, 3, 4, 0]])
palette[image]

array([[[  0,   0,   0],
        [255,   0,   0],
        [  0, 255,   0],
        [  0,   0,   0]],

       [[  0,   0,   0],
        [  0,   0, 255],
        [255, 255, 255],
        [  0,   0,   0]]])

In [131]:
a = np.arange(12).reshape(3, 4)
a
i = np.array([[0, 1],
              [1, 2]])
j = np.array([[2, 1],
              [3, 3]])
a[i, j]
a[i, 2]
a[:, j]

array([[[ 2,  1],
        [ 3,  3]],

       [[ 6,  5],
        [ 7,  7]],

       [[10,  9],
        [11, 11]]])

In [3]:
a = np.array([10, 20, 30, 40, 50])
indices = [0, 2, 4]
print(a[indices])

[10 30 50]


In [4]:
a = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
rows = np.array([0, 1, 2])
cols = np.array([2, 1, 0])
print(a[rows, cols])

[3 5 7]


In [5]:
a = np.array([[10, 20, 30], [40, 50, 60], [70, 80, 90]])
rows = np.array([0, 2])
cols = np.array([1, 2])
ixgrid = np.ix_(rows, cols)
print(a[ixgrid])

[[20 30]
 [80 90]]


In [8]:
a = np.array([(1, 2.0, 'A'), (2, 3.0, 'B')], dtype=[('x', 'i4'), ('y', 'f4'), ('z', 'U1')])
print(a['x'])
print(a['z'])

[1 2]
['A' 'B']


In [7]:
a = np.array([1, 2, 3, 4])
print(np.add.reduce(a))

10
